[package]
name = "brother-label"
description = "CLI to print images using Brother QL series printers based on the brother_ql crate"
version = "0.3.2"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
anyhow = "1.0.104"
brother_ql = { version = "3.0.5", path = "../brother_ql", features = [
  "clap",
  "usb",
  "test-labels",
] }
clap = { version = "4.6.6", features = ["derive"] }
image = "0.25.10"
tracing-subscriber = { version = "0.3.23", features = [
  "tracing",
  "env-filter",
] }
